// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockAnalyzer.Infrastructure.Persistence;

#nullable disable

namespace StockAnalyzer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StockAnalyzerDbContext))]
    [Migration("20260611071029_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockAnalyzer.Domain.Stocks.ModelMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<string>("ConfusionMatrix")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureImportance")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precision")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<decimal>("Recall")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "CreatedAt");

                    b.ToTable("ModelMetrics", (string)null);
                });

            modelBuilder.Entity("StockAnalyzer.Domain.Stocks.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualResult")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("actual_result");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PredictionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("prediction_type");

                    b.Property<string>("PredictionValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prediction");

                    b.Property<decimal?>("ProbabilityDown")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("probability_down");

                    b.Property<decimal?>("ProbabilityUp")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("probability_up");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_id");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "CreatedAt");

                    b.ToTable("Predictions", (string)null);
                });

            modelBuilder.Entity("StockAnalyzer.Domain.Stocks.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("StockAnalyzer.Domain.Stocks.StockPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Date")
                        .IsUnique();

                    b.ToTable("StockPrices", (string)null);
                });

            modelBuilder.Entity("StockAnalyzer.Domain.Stocks.ModelMetric", b =>
                {
                    b.HasOne("StockAnalyzer.Domain.Stocks.Stock", "Stock")
                        .WithMany("ModelMetrics")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockAnalyzer.Domain.Stocks.Prediction", b =>
                {
                    b.HasOne("StockAnalyzer.Domain.Stocks.Stock", "Stock")
                        .WithMany("Predictions")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockAnalyzer.Domain.Stocks.StockPrice", b =>
                {
                    b.HasOne("StockAnalyzer.Domain.Stocks.Stock", "Stock")
                        .WithMany("Prices")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockAnalyzer.Domain.Stocks.Stock", b =>
                {
                    b.Navigation("ModelMetrics");

                    b.Navigation("Predictions");

                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
